name: Zip and put in S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    # Name the Job
    name: Zip Files
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: main.py
          recursive: false
          dest: main.zip

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
