name: Zip and put in S3

on:
  push:
    branches:
      - master

jobs:
  packaging:
    # Name the Job
    name: Zip Files
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: main.py
          recursive: false
          dest: main.zip
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/main.zip
      - uses: qoqa/action-s3-cp@v1.1
        env:
          FILE: ./main.zip
          AWS_REGION: 'us-east-1'
          AWS_S3_BUCKET: my.lambda.deployment.bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: List 
        run: ls -lrt
   
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install AWS
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
      - run: aws --version
        shell: bash
      - run: aws s3api get-object --bucket my.lambda.deployment.bucket --key main.zip main.zip
        with:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        shell: bash
      - run: ls -lrt
      #- run: aws lambda create-function --function-name my-function1 --zip-file fileb://main.zip --handler index.handler --runtime python3.8 --role arn:aws:iam::876053156279:role/lambda-ex
      # - name: default deploy
      #   uses: appleboy/lambda-action@master
      #   with:
      #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws_region: us-east-1
      #     function_name: my-function
      #     zip_file: s3://my.lambda.deployment.bucket/main.zip
    #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ################################
      # Run Linter against code base #
      ################################
      #- name: Lint Code Base
      #  uses: github/super-linter@v4
      #  env:
      #    VALIDATE_ALL_CODEBASE: false
      #    DEFAULT_BRANCH: master
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
