name: Zip and put in S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    # Name the Job
    name: Zip Files
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: main.py
          recursive: false
          dest: main.zip
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/main.zip
      - uses: qoqa/action-s3-cp@v1.1
        env:
          FILE: ./main.zip
          AWS_REGION: 'us-east-1'
          AWS_S3_BUCKET: my.lambda.deployment.bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
